### PR TITLE
Migrate from puppeteer to playwright.

### PR DESCRIPTION
**Pull request by anicolao**
Verified that puppeteer is completely gone afterwards with:

git grep puppet

Some mysteries:

`make test-spec` now takes ~20% longer (3.6s vs 3.2s)
Code coverage reported rises from ~60% to ~70%

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks! This looks and works great. Two things:

1. Could you re-add `@web/test-runner` as a test dependency?
2. Would you mind granting GPL+MPL for your contributions at https://github.com/cubing/cubing.js/issues/208#issue-1352819115 ?

**Review by anicolao — COMMENTED** [review]
Add @web/test-runner back as a dev dependency. First time I’ve ever done this in the web editor invoked by vscode … through some magic, it has all my normal vscode settings and extensions even though I’ve never used it before! I will check it on a computer momentarily to make sure this worked as expected.

**Comment by anicolao** [comment]
Well I didn't quite figure out the in-browser vscode, so it was simpler to just get a laptop and finish the job. I think this commit is now ready to go.

**Comment by lgarron** [comment]
Alright, this is looking good, thanks! :-D

**Pull request merged**
