### PR TITLE
Add support for exporting permutations to Mathematica

### PR DESCRIPTION
**Pull request by benwh1**

### CODE REVIEW

**Comment by lgarron** [comment]
Looking good!

```mathematica
FactorInteger[GroupOrder[PermutationGroup[gen]]/43252003274489856000]
{{2, 14}, {3, 1}}
```

2^12 of those are from center orientation (4^6); do you know why that leaves only a factor of 12 rather than 24?

**Comment by benwh1** [comment]
> 2^12 of those are from center orientation (4^6); do you know why that leaves only a factor of 12 rather than 24?

It's not possible to only rotate one center by 90 degrees

**Comment by lgarron** [comment]
> > 2^12 of those are from center orientation (4^6); do you know why that leaves only a factor of 12 rather than 24?
> 
> It's not possible to only rotate one center by 90 degrees

Ah, yes, that would do it! For some reason I was dividing the 48 by 2, but not the 4^6. 🤦

In any case, I'll leave final approval and merging to @rokicki

**Comment by rokicki** [comment]
Ben, can you make the same change as 4697f79da63feb3c688d73b4d70f76d8b91e3a4d to your toMathematica function in this pull request before we integrate?  This way i can test full functionality before approving.  Thanks!

The test here would be:  PermutationOrder[PermutationProduct[mU, mF, mR]]

This should return 80.  With the current code it is returning 84.

**Pull request merged**
