### PR TITLE
Add scramblers by @torchlight (a.k.a. `xyzzy`).

### PR DESCRIPTION
**Pull request by lgarron**

### CODE REVIEW

**Comment by lgarron** [comment]
@torchlight, could I ask you to confirm that you are the author of all the code in the added scrambling files, and that you're happy to add them to `cubing.js` under the project license (GPL)?

**Comment by torchlight** [comment]
Yes, I am the sole author of the added scrambling files, and agree to have them added under the GPL.

**Comment by lgarron** [comment]
> Yes, I am the sole author of the added scrambling files, and agree to have them added under the GPL.

Thanks! ☺️

**Comment by lgarron** [comment]
@torchlight, for https://github.com/cubing/cubing.js/issues/208 could I ask you to confirm that you're also happy to license your scramblers under the MPL?

**Comment by torchlight** [comment]
Yes, the MPL is also fine with me.

**Pull request merged**
