### PR TITLE
Consider using BigInt constructor for compatibility.

### PR DESCRIPTION
**Pull request by anicolao**

### CODE REVIEW

**Review by rokicki — APPROVED** [review]
This does enhance the ability to find BitInt stuff in the code.  I'm pretty sure typescript "does the right thing" here with respect to literals but even if it doesn't, it's not going to affect performance.

**Comment by lgarron** [comment]
Thanks! I'm glad this is actually such a simple fix.

I will maintain that projects like Vite are broken if they break big-int code, given that it's been available in all environments for 2 years: https://caniuse.com/?search=bigint  
For that reason, I'm generally against workarounds like this in our codebase. But I think this one is definitely worth it, thanks for looking into it!

**Comment by lgarron** [comment]
Published as part of `v0.29.1`!
https://github.com/cubing/cubing.js/releases/tag/v0.29.1

**Comment by anicolao** [comment]
Even after reading that thread I don't understand why there are two different environments to configure for vite - the `optimizeDeps` vs the `build` ... but in any event I'm glad to have the workaround in 0.29.1! Thanks.

**Pull request merged**
