### PR TITLE
Specify that `es2020` is required

### LINKED ISSUE #192: Cubing.js not working with vite
### Scroll down to the third post in this thread to see the location of the issue, and the fourth post for a workaround

**To Reproduce**

1. Create a new vanilla TypeScript project with vite.
2. Install `cubing.js`
3. Import `cubing.js` in `index.ts`
4. Restart dev server

Vite throws this error:
```
          ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
          
              node_modules/cubing/dist/esm/chunk-TB6NTLZY.js:578:10:
                578 │   let r = 1n;
                    ╵           ~~
          
          ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
          
              node_modules/cubing/dist/esm/chunk-TB6NTLZY.js:949:12:
                949 │     let n = 1n;
                    ╵             ~~
          
          ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
          
              node_modules/cubing/dist/esm/chunk-TB6NTLZY.js:1808:13:
                1808 │     let sz = 1n;
                     ╵              ~~
          
          ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
          
              node_modules/cubing/dist/esm/chunk-TB6NTLZY.js:1811:11:
                1811 │       sz = 1n;
```
**Expected behavior**
`cubing.js` is imported.

**Browser:**
- OS: Windows 11
- Browser Chrome/Edge 103

**Screenshots**
image

### PR DESCRIPTION
**Pull request by debater-coder**
Closes #192

### CODE REVIEW

**Comment by debater-coder** [comment]
Either this, or we could make a FAQ.

**Comment by debater-coder** [comment]
#192

**Comment by debater-coder** [comment]
closes #192

**Comment by debater-coder** [comment]
What I have done is added that if you are using a bundler you must set it to use `es2020`. I have put this under its own section for clarity. Maybe if we could add more troubleshooting problems like this we could make a FAQ, but because its only one problem the user may encounter, I've put it in its own section.

**Comment by debater-coder** [comment]
This is my first PR in an open source project. 🥳

**Comment by debater-coder** [comment]
> Would you be able to update this, taking all that into account?
Yes, I'll update it as soon as possible.

**Comment by debater-coder** [comment]
Okay, so now I've moved the section to index.html, and I've kept the details on Vite as minimal as possible.

**Comment by lgarron** [comment]
So, I spent some time this week trying to get Vite to have full compatibility with `es2020`, and did not succeed.

From https://github.com/vitejs/vite/issues/9062 it sounds like we won't work in Vite out of the box until Vite 4 — and Vite 3 is barely released. I wanted to be able to recommend Vite as a bundler in our docs, but I have to give up on that for now, and I'm reluctant to mention them all if we have such reservations. :-/

I'd like to keep thinking about this, apologies for the delay.

**Pull request merged**
